Feature/occupy dj seat
turntablefm/turntable pull request #47
Opened 2020-10-22 12:39 UTC by JaHajRF

Saga that reacts to message and sets DJ seat added

2020-10-22 15:28 UTC, SzymonJaworskiRF commented on packages/webapp/.eslintrc.json
> +    "react-hooks/exhaustive-deps": "off",
We definitely can't disable this rule as it prevents many errors.

2020-10-22 15:34 UTC, SzymonJaworskiRF commented on packages/webapp/src/containers/DjSeat.tsx
> +          const currentDjSeat = djSeats.get(djSeatKey)!
Please handle error in either `if` clause or via optional chaining.

2020-10-22 15:35 UTC, SzymonJaworskiRF commented on packages/webapp/src/containers/DjSeat.tsx
> +            <div key={`dj-seat-${djSeatKey}`}>
We don't render list here, so is the `key` prop necessary?

2020-10-22 15:42 UTC, SzymonJaworskiRF commented on packages/webapp/src/services/isCurrentSeatValid.ts
> +import hash from 'object-hash'
I don't think this function is a service. We should consider moving it somewhere else.

2020-10-22 15:45 UTC, SzymonJaworskiRF commented on packages/webapp/src/services/isCurrentSeatValid.ts
> +  const currentHash = hash(currentDjSeat).charCodeAt(0)
This is not a hash, rather it's first letter representation in UTF-16 format.

2020-10-22 15:46 UTC, SzymonJaworskiRF commented on packages/webapp/src/services/isCurrentSeatValid.ts
> +  return currentHash > newHash
What happens if we generated 2 hashes with the same first letter? Is it possible 2 users will see that they can seat on a DJ seat then?

2020-10-22 15:48 UTC, SzymonJaworskiRF commented on packages/webapp/src/store/sagas/djSeats.ts
> +  isCurrentSeatValid(djSeat, newDjSeat)
What is the point of this function here?

2020-10-22 15:49 UTC, SzymonJaworskiRF commented on packages/webapp/src/store/sagas/djSeats.ts
> +  const djSeat = ((yield select(djSeatsSelectors.djSeats)) as Map<number, DjSeat>).get(action.payload.djSeatKey)
We've talked about switching to `typed-redux-saga` to avoid problems with missing types after `yield`. Can we do that as soon as possible?

2020-10-22 15:50 UTC, SzymonJaworskiRF commented on packages/webapp/src/store/reducers/djSeats.ts
>  // eslint-disable-next-line no-empty-function
I believe this comment is unnecessary now.

2020-10-22 15:51 UTC, SzymonJaworskiRF requested changes
Some issues need to be addressed before we can merge.

2020-10-23 06:18 UTC, JaHajRF commented on packages/webapp/src/containers/DjSeat.tsx
> +          const currentDjSeat = djSeats.get(djSeatKey)!
What is the benefit of this approach? As we know that this variable always exists as we map through djSeats keys.

2020-10-23 06:19 UTC, JaHajRF commented on packages/webapp/src/containers/DjSeat.tsx
> +            <div key={`dj-seat-${djSeatKey}`}>
We do render list here. This depends on amount of seats in redux state. Currently we have 1 seat but this will change in future

2020-10-23 06:26 UTC, JaHajRF commented on packages/webapp/src/services/isCurrentSeatValid.ts
> +  return currentHash > newHash
If so than this statement (e.g. 130 < 130) will return false, and a new DJ will sit on DJ seat. So it will be consistent across all the peers

2020-10-23 06:27 UTC, JaHajRF commented on packages/webapp/src/store/sagas/djSeats.ts
> +  isCurrentSeatValid(djSeat, newDjSeat)
It's dummy call placed there to invoke a function for debugging purpose. To delete

2020-10-23 06:29 UTC, JaHajRF commented on packages/webapp/.eslintrc.json
> +    "react-hooks/exhaustive-deps": "off",
Issue #52 created for that

2020-10-23 06:30 UTC, JaHajRF commented on packages/webapp/.eslintrc.json
> +    "react-hooks/exhaustive-deps": "off",
Issue #50 created for that.

2020-10-23 06:31 UTC, JaHajRF commented on packages/webapp/src/store/sagas/djSeats.ts
> +  const djSeat = ((yield select(djSeatsSelectors.djSeats)) as Map<number, DjSeat>).get(action.payload.djSeatKey)
Isse #52 created for that

2020-10-23 10:04 UTC, merged